-- 코드를 작성해주세요
SELECT BF.ROUTE, 
    CONCAT(BF.TOTAL_DISTANCE, "km") AS TOTAL_DISTANCE, 
    CONCAT(BF.AVERAGE_DISTANCE, "km") AS AVERAGE_DISTANCE
FROM (SELECT ROUTE,
      ROUND(SUM(D_BETWEEN_DIST), 1) AS TOTAL_DISTANCE,
      ROUND(AVG(D_BETWEEN_DIST), 2) AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY TOTAL_DISTANCE DESC) BF
